export const GOODS_EXIT_LARGE_QUANTITY_THRESHOLD = Number(
  process.env.GOODS_EXIT_LARGE_QUANTITY_THRESHOLD ?? 50,
);

export const GOODS_EXIT_LARGE_VALUE_THRESHOLD_XOF = Number(
  process.env.GOODS_EXIT_LARGE_VALUE_THRESHOLD_XOF ?? 100_000,
);

export const ASSET_HIGH_VALUE_EXIT_THRESHOLD_XOF = Number(
  process.env.ASSET_HIGH_VALUE_EXIT_THRESHOLD_XOF ?? 200_000,
);
