FROM node:22-alpine
WORKDIR /app

COPY package*.json nest-cli.json tsconfig*.json prisma.config.ts ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate

COPY . .

EXPOSE 3001
CMD ["npm", "run", "start:dev"]
