export const CONTRACT_VALIDATION_AMOUNT_THRESHOLD_XOF = Number(
  process.env.CONTRACT_VALIDATION_AMOUNT_THRESHOLD_XOF ?? 500_000,
);

export const CONTRACT_EXPIRY_WARNING_DAYS = Number(
  process.env.CONTRACT_EXPIRY_WARNING_DAYS ?? 30,
);
